### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by Sciss** [riebl/vmu931#1]
Sorry to 'abuse' the issue tracker for this. I would like to enquire if you are using the VMC931 under Linux? I read there were some initial problems but that they have been fixed; I'm eying the VMC, so I want to be sure I see people using it successfully under Linux. Thanks

**Comment by riebl** [comment]
Yes, I am using the VMU931 under Linux without any (big) issues so far. The IMU shows up as USB serial device. I have only noticed that it does not like to send and receive data concurrently (full duplex). For this reason my library does only half duplex communication. Since I need to send some configuration commands only in the beginning this is not a show-stopper for me.

**Comment by Sciss** [comment]
Thank you!
